sudo: required
services:
  - docker
# build and run tests
before_install:
  - docker build -t caleboconnell/alna-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true caleboconnell/alna-test npm test 
# build prod images
after_success:
  - docker build -t caleboconnell/alna-client ./client
  - docker build -t caleboconnell/alna-nginx ./nginx
  - docker build -t caleboconnell/alna-server ./server
  - docker build -t calebovonnell/alna-worker ./worker
# Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push to docker hub
  - docker push caleboconnell/alna-client
  - docker push caleboconnell/alna-nginx
  - docker push caleboconnell/alna-server
  - docker push caleboconnell/alna-worker