sudo: required
services:
  - docker
# build and run tests
before_install:
  - docker build -t caleboconnell/alna-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true caleboconnell/alna-test npm test 
# build prod images
after_success:
  - docker build -t caleboconnell/alna-client ./client
  - docker build -t caleboconnell/alna-nginx ./nginx
  - docker build -t caleboconnell/alna-server ./server
  - docker build -t caleboconnell/alna-worker ./worker
# Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push to docker hub
  - docker push caleboconnell/alna-client:latest
  - docker push caleboconnell/alna-nginx:latest
  - docker push caleboconnell/alna-server:latest
  - docker push caleboconnell/alna-worker:latest

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: alna-app
  env: AlnaApp-env
  bucket_name: elasticbeanstalk-us-east-1-013962559831
  bucket_path: alna-app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY